spring:
  datasource:
    url: jdbc:mysql://118.178.142.156:3306/test_my?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 88GteF34iM2H8g01x
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
        id:
          new_generator_mappings: true
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace