server:
  port: 8080

spring:
  rabbitmq:
    host: 47.99.217.240
    port: 5672
    username: admin
    password: admin
    virtual-host: my-cloud
    template:
      retry:
        enabled: true
        initial-interval: 1s
      exchange: cloud-exchange
      routing-key: cloud-routing-key
      default-receive-queue: cloud-queue
    publisher-returns: false
    listener:
      type: direct
      direct:
        retry:
          enabled: true

file:
  upload:
    config:
      imageUrl: http://47.96.77.229:9300/file/upload?action=upload
      imagePath:
      imageFieldName: file
      imageMaxSize: 10485760
      imageAllowFiles:
        - .png
        - .jpg
        - .jpeg
        - .gif
        - .bmp